name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: |
        dotnet restore CliReader/CliReader.csproj
        dotnet restore Replay.Encoding.Tests/Replay.Encoding.Tests.csproj
        dotnet restore Replay.Unreal.Tests/Replay.Unreal.Tests.csproj
        dotnet restore Replay.Valorant.Tests/Replay.Valorant.Tests.csproj
    - name: Build
      run: dotnet build CliReader/CliReader.csproj --no-restore
    - name: Test
      run: |
        dotnet test Replay.Encoding.Tests/Replay.Encoding.Tests.csproj --no-restore --verbosity normal
        dotnet test Replay.Unreal.Tests/Replay.Unreal.Tests.csproj --no-restore --verbosity normal
        dotnet test Replay.Valorant.Tests/Replay.Valorant.Tests.csproj --no-restore --verbosity normal
